version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.5
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: install python dependence
          command:  |
            python3 -m venv venv
            . ven/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"