version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.5
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: install python dependence
          command:  |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: excute unit test
          command:  |
            . venv/bin/activate
            cd src && python -m pytest
          environment:
            WORK_ENV: TEST
      - store_test_results:
          path: test-results
      - run:
          name: build image
          command: |
            docker build -t multimedia-manager-backend .
      - run:
          name: save docker image
          command: |
            mkdir -p ./caches
            docker save -o ./caches/multimedia-manager-backend.tar multimedia-manager-backend
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - ./caches/multimedia-manager-backend.tar