version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.5
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: install python dependence
          command:  |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: excute unit test
          command:  |
            sudo mkdir -p /var/log/multimedia
            echo "user: `whoami`"
            echo "`ls -l /var/log/multimedia`"
            sudo chown -R $USER:$USER /var/log/multimedia
            echo "user: `whoami`"
            echo "`ls -l /var/log/multimedia`"
            . venv/bin/activate
            cd src && python -m pytest
          environment:
            WORK_ENV: TEST
      - store_test_results:
          path: test-results